### ISSUE TITLE
[Bug] Null records in the Ad Group Report Model

### ISSUE THREAD

**Issue by paritushPXGContractor** [fivetran/dbt_microsoft_ads#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We are encountering null values in "ad_group_id" column after "microsoft_ads__ad_group_report" runs. After investigating we found out it uses 2 tables for "ad_group_id" column and its a left join between "stg_microsoft_ads__ad_group_daily_report" & "stg_microsoft_ads__ad_group_history". Both of these tables didn't have any null values in them. Also, in the source left table "stg_microsoft_ads__ad_group_daily_report", we have more than 300,000 records, and after the left join, we are left with around 150,000 records with 1700 records of nulls in the final table microsoft_ads__ad_group_report. 

### Relevant error log or model output

```shell
12:33:47  9 of 118 START test not_null_ad_reporting__ad_group_report_ad_group_id ......... [RUN]
12:33:49  9 of 118 FAIL 419 not_null_ad_reporting__ad_group_report_ad_group_id ........... [FAIL 419 in 1.54s]
```

### Expected behavior

There shouldn't be any nulls and the rows count ideally shouldn't change from the left table in a left join.

### dbt Project configurations
```yml
name: 'microsoft_ads'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  microsoft_ads:
    account_history: "{{ ref('stg_microsoft_ads__account_history') }}"
    account_performance_daily_report: "{{ ref('stg_microsoft_ads__account_daily_report') }}"
    campaign_history: "{{ ref('stg_microsoft_ads__campaign_history') }}"
    campaign_performance_daily_report: "{{ ref('stg_microsoft_ads__campaign_daily_report') }}"
    ad_group_history: "{{ ref('stg_microsoft_ads__ad_group_history') }}"
    ad_group_performance_daily_report: "{{ ref('stg_microsoft_ads__ad_group_daily_report') }}"
    ad_history: "{{ ref('stg_microsoft_ads__ad_history') }}"
    ad_performance_daily_report: "{{ ref('stg_microsoft_ads__ad_daily_report') }}"
    keyword_history: "{{ ref('stg_microsoft_ads__keyword_history') }}"
    keyword_performance_daily_report: "{{ ref('stg_microsoft_ads__keyword_daily_report') }}"
    search_performance_daily_report: "{{ ref('stg_microsoft_ads__search_daily_report') }}"

  microsoft_ads_auto_tagging_enabled: false

  microsoft_ads__account_report_passthrough_metrics: []
  microsoft_ads__campaign_report_passthrough_metrics: []
  microsoft_ads__ad_group_report_passthrough_metrics: []
  microsoft_ads__ad_report_passthrough_metrics: []
  microsoft_ads__keyword_report_passthrough_metrics: []
  microsoft_ads__search_report_passthrough_metrics: []


models:
  microsoft_ads:
    +schema: microsoft_ads
    +materialized: table

```
### Package versions

packages:
  - package: fivetran/microsoft_ads_source
    version: [">=0.6.0", "<0.7.0"]

### What database are you using dbt with?

redshift

### dbt Version

DBT version 1.2

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
